### ISSUE TITLE
Add linking parameters to IIIF manifests

### ISSUE THREAD

**Issue by ahankinson** [ArchiveLabs/iiif.archivelab.org#10]
It would be great to have the `related` and `seeAlso` links in the generated manifests. The first would allow external services to link back to the record on the IA site; the second would provide access to machine-readable information about the object. 

`rendering` could also point to the PDF version of the object available on the IA site.

**Comment by mekarpeles** [comment]
This should be doable without too much hard work. The IIIF API could be used to generate the pdf version (we can add that link as `rendering`).

re: related we should be able to link back to the original item fairly easily (since the IIIF ids are the same as the archive.org ids). seeAlso can be generated with the item's metadata (i.e. archive.org/metadata/:id)
