### ISSUE TITLE
Making Internet Archived Archived Images Served via IIIF

### ISSUE THREAD

**Issue by ekansa** [ArchiveLabs/iiif.archivelab.org#16]
Hi, 

We met at the "Library Leaders" meeting at the Internet Archive last week, and I'm working on getting images (and metadata) from Open Context (https://opencontext.org) over to you all for IIIF hosting (and archiving). I've got a test picture up here: https://archive.org/details/opencontext-test-item

How can I make the images I upload working with the IIIF hosting?

Thanks!
-Eric

**Comment by mekarpeles** [comment]
https://iiif.archivelab.org/iiif/opencontext-test-item should open the image in openseadragon. The item was uploaded as "community texts". Make sure you upload them as "community media" (otherwise it will try to open it as if the item is a text (book) instead of an image.

From https://iiif.archivelab.org/iiif/opencontext-test-item you can apply the IIIF Image specification parameters (e.g. https://iiif.archivelab.org/iiif/opencontext-test-item/full/full/!0/default.jpg) to cite regions of the image, etc.

See documentation at http://iiif.archivelab.org/iiif/documentation

**Comment by ekansa** [comment]
Thanks!!
-E
